import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
});

export const metadata: Metadata = {
  title: "Igualdad de Género",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={geistSans.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
